# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={},
        ),
    ]
