# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20170813_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='documents',
            name='trash',
            field=models.BooleanField(default=True),
        ),
    ]
