# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20170718_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='journals',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Não Informado'), (1, 'Informação & Sociedade'), (2, 'Transinformação'), (3, 'Perspectivas em Ciência da Informação')], default=0),
        ),
    ]
