# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20170902_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
