# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_documents_journals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='journals',
            new_name='journal',
        ),
    ]
