# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_auto_20170907_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='order',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='authors_v2',
        ),
        migrations.AddField(
            model_name='authormember',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Author'),
        ),
        migrations.AddField(
            model_name='authormember',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Documents'),
        ),
        migrations.AddField(
            model_name='documents',
            name='authors_v3',
            field=models.ManyToManyField(through='journals.AuthorMember', to='journals.Author'),
        ),
    ]
