# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_normalize_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='journal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Não Informado'), (1, 'Informação & Sociedade'), (2, 'Transinformação'), (3, 'Perspectivas em Ciência da Informação'), (4, 'Informação & Informação'), (5, 'Em Questão'), (6, 'Ágora'), (7, 'InCID: Revista de Ciência da Informação e Documentação'), (8, 'Intexto'), (9, 'Tendências da Pesquisa Brasileira em Ciência da Informação'), (10, 'Revista Brasileira de Biblioteconomia e Documentação'), (11, 'BRAZILIAN JOURNAL OF INFORMATION SCIENCE: RESEARCH TRENDS'), (12, 'Ponto de Acesso'), (13, 'Revista Ibero-Americana de Ciência da Informação'), (14, 'Revista ACB'), (15, 'Biblios')], default=0),
        ),
    ]
