# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_auto_20170907_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='authors_v3',
            field=models.ManyToManyField(default=None, through='journals.AuthorMember', to='journals.Author'),
        ),
        migrations.AddField(
            model_name='documents',
            name='keywods_v1',
            field=models.ManyToManyField(default=None, to='journals.Keyword'),
        ),
    ]
