# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_auto_20170909_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='url_view',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
