# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_auto_20170910_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
