# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0013_populate_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal'),
        ),
    ]
